### ISSUE TITLE
puppet login failed

### ISSUE THREAD

**Issue by su27k-2003** [padlocal/wechaty-puppet-padlocal#60]
Hi, I was using PuppetPadlocal for the past few days without any issues but got the error below today. Could you help me understand what caused the error? Thank you.
My PadLocal Token Gateway server host in Hong Kong (GCP) and I'm accessing it from Australia. Sounds like we had a similar issue (https://github.com/padlocal/wechaty-puppet-padlocal/issues/37) in the past. 

14:53:50 ERR [PuppetPadlocal] login failed: VError: [tid:3c24ed33] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:3c24ed33] wechat bad request er
ror
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (events.js:314:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:483:12)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:666:18)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
14:53:50 VERB StateSwitch <PuppetPadlocal> off(pending) <- (false)
14:53:50 VERB [LongLink] [undefined] longlink shutdown
14:53:50 VERB StateSwitch <PuppetPadlocal> off(true) <- (pending)

**Comment by su27k-2003** [comment]
@padlocal thank you

**Comment by padlocal** [comment]
> @padlocal is that issue caused by foreign IP as same as the issue#37? 
> 
> thank you.

no，it's different. We are investigating. Can you help us to debug if needed?

**Comment by su27k-2003** [comment]
Sure thing, happy to help. Let me know what you need from my end. Thanks.

**Comment by su27k-2003** [comment]
Hi @padlocal just a quick update here.
I've created a new PadLocal Token Gateway server with different IP (a new server in a different region - Taiwan) and confirmed the error still present. It indicates that probably something wrong with the WECHATY_PUPPET_PADLOCAL_TOKEN authentication rather than the PadLocal Token Gateway server itself. 
Let me know if you need any info from my end to help you investigate the issue. Thanks.
 
23:58:06 ERR [PuppetPadlocal] login failed: VError: [tid:723d622f] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:723d622f] wechat bad request error
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (events.js:314:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:483:12)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:666:18)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by padlocal** [comment]
Thanks for your updating, we are working on this.

**Comment by padlocal** [comment]
Fixed, please have a try.

**Comment by su27k-2003** [comment]
Hi @padlocal 

I've tried and confirmed the same issue still present at my end. Please refer to the error message below:

23:16:37 ERR [PuppetPadlocal] login failed: VError: [tid:c5dbc8a0] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:c5dbc8a0] wechat bad request error
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (events.js:314:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:483:12)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:666:18)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by su27k-2003** [comment]
@suntong could you test it from your end as well? just for double-checking. Thank you.

**Comment by suntong** [comment]
Yep, same here as well:

```
       - wechaty-puppet-padlocal version: 0.2.42
       - padlocal-ts-client version: 0.2.30

23:53:44 INFO StarterBot onScan: Scanned(3)
23:53:50 INFO StarterBot onScan: Confirmed(4)
(node:1285) UnhandledPromiseRejectionWarning: VError: [tid:a39fda9a] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:a39fda9a] wechat request io error
    at Request._failAllPendingRequest (/path/to/wechaty-examples/node_modules/wechaty/node_modules/padlocal-client-ts/dist/Request.js:262:19)
    at ClientDuplexStreamImpl.<anonymous> (/path/to/wechaty-examples/node_modules/wechaty/node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (events.js:315:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:467:12)
    at Object.onReceiveStatus (/path/to/wechaty-examples/node_modules/wechaty/node_modules/@grpc/grpc-js/build/src/client.js:387:28)
    at Object.onReceiveStatus (/path/to/wechaty-examples/node_modules/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /path/to/wechaty-examples/node_modules/wechaty/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

**Comment by padlocal** [comment]
> Yep, same here as well:
> 
> ```
>        - wechaty-puppet-padlocal version: 0.2.42
>        - padlocal-ts-client version: 0.2.30
> 
> 23:53:44 INFO StarterBot onScan: Scanned(3)
> 23:53:50 INFO StarterBot onScan: Confirmed(4)
> (node:1285) UnhandledPromiseRejectionWarning: VError: [tid:a39fda9a] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:a39fda9a] wechat request io error
>     at Request._failAllPendingRequest (/path/to/wechaty-examples/node_modules/wechaty/node_modules/padlocal-client-ts/dist/Request.js:262:19)
>     at ClientDuplexStreamImpl.<anonymous> (/path/to/wechaty-examples/node_modules/wechaty/node_modules/padlocal-client-ts/dist/Request.js:56:18)
>     at ClientDuplexStreamImpl.emit (events.js:315:20)
>     at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:467:12)
>     at Object.onReceiveStatus (/path/to/wechaty-examples/node_modules/wechaty/node_modules/@grpc/grpc-js/build/src/client.js:387:28)
>     at Object.onReceiveStatus (/path/to/wechaty-examples/node_modules/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
>     at /path/to/wechaty-examples/node_modules/wechaty/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
>     at processTicksAndRejections (internal/process/task_queues.js:75:11)
> ```

Could you please try again, we fixed it again.

**Comment by padlocal** [comment]
> Hi @padlocal
> 
> I've tried and confirmed the same issue still present at my end. Please refer to the error message below:
> 
> 23:16:37 ERR [PuppetPadlocal] login failed: VError: [tid:c5dbc8a0] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:c5dbc8a0] wechat bad request error
> at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
> at ClientDuplexStreamImpl. (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
> at ClientDuplexStreamImpl.emit (events.js:314:20)
> at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:483:12)
> at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:666:18)
> at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
> at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
> at processTicksAndRejections (internal/process/task_queues.js:79:11)

This issue is different as @suntong 's one, working on it

**Comment by padlocal** [comment]
@su27k-2003 Fixed

**Comment by su27k-2003** [comment]
@padlocal Thanks.

confirmed that the PadLocal Token Gateway is working without error now. But my wechaty python script (bot) generated the error below and the bot cannot send messages out anymore.
As I didn't change the python script and the python script worked properly before we had the PadLocal Token Gateway issue#60, I suspect the change made for issue#60 caused the wechaty python error? Please let me know if you have any idea from the error message. Thanks. Happy to raise the issue with the wechaty python project if you think it's unrelated to the wechaty-puppet-padlocal.

2021-04-12 22:31:04,394 - Wechaty - ERROR - internal error <(<Status.INTERNAL: 13>, '[tid:2bf0d6f4] request has been cancelled for reason: CLIENT_ERROR: [tid:2bf0d6f4] Exception while handling wechat request: [tid:2bf0d6f4] Fail to request short link for path:/mmtls/fff12b0e, data: 19f10300a10000009d0103f10100a8dc871d72a6c169757d25be45170dd83c99fe4a4b7cdecd8d7a078919a3b7ed7360743d7c0000006f010000006a000f01000000630100093a8000000000003d000c760485b1f9cfbb94ab284ae700481cef2f3f5e5e354ec0a86f2c47fb26174683d940f75a1dc72775b21b627626f5f445374549c0fe9a704b147cd7b151c7433b746942c2df843bb9a440f533ed5dfeeeeae983ed2bc719f1030024b205b223ffdd198f0c284ceb01138f66d538d9fc4fa049f2544a405c6689f4332b3a636517f10300cdda29519dcd8d5833a379c67ebf941ace61627d361a9f4496274549226d52c51d1b3dedde00d8d21761f111fa87a89c17acbf2221252cf54e0831389a08ec26c025a5e4e0fee5729ccf09cb34f3537dab8d87a3428b2cd6b8989af0f7a96c537eac3da52ecb404b849cf1f7a3b6558ff3e9d3b5d083fdf1eb08427b4e86786c80d5df6e006645697b47688b5102260f1ec2c26e81ec869d7d78447c10b8bd09bf9cee50ccb3b2df1573cedc472d1fba18c255af2db3da7e3a0a7b5ea5e6fcfdfd61715bb2cb3dccca9b4ff5416915f10300171159eae3e7fc224bd83daca00bccabe0198147ee2ac520, after max retry:5: ENOTFOUND: getaddrinfo ENOTFOUND sgextshort.wechat.com', None)>

**Comment by suntong** [comment]
Login problem is fixed. 

But login won't stay steady. Will get into exactly as what @su27k-2003 reported. 

Let's close this one as the login problem has in fact been fixed. 
I'll open another one.

**Comment by emilsong** [comment]
本地macbook没问题，但是放到centos服务器上不论什么IP都无法登录

13:08:11 ERR [Request] [tid:a677307a], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:a677307a] wechat request io error
13:08:11 WARN [LongLink] [] close connection on error,IOError: long link init failed: [tid:a677307a] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:a677307a] wechat request io error
13:08:11 WARN [LongLink] longlink reconnect [1] after delay:1000ms
13:08:11 ERR [Request] [tid:38abba96], padlocal grpc request failed: 3, error: IOError: [tid:38abba96] Exception while handling wechat request: long link init failed: [tid:a677307a] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:a677307a] wechat request io error
13:08:11 ERR [PadLocalClient] error while syncing onpush: VError: [tid:38abba96] request has been cancelled for reason: CLIENT_ERROR: [tid:38abba96] Exception while handling wechat request: long link init failed: [tid:a677307a] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:a677307a] wechat request io error
    at Request._failAllPendingRequest (/opt/chat/node_modules/padlocal-client-ts/dist/Request.js:265:19)
    at Request.error (/opt/chat/node_modules/padlocal-client-ts/dist/Request.js:275:14)
    at Request.<anonymous> (/opt/chat/node_modules/padlocal-client-ts/dist/Request.js:159:30)
    at Generator.throw (<anonymous>)
    at rejected (/opt/chat/node_modules/padlocal-client-ts/dist/Request.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
VError: [tid:a677307a] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:a677307a] wechat request io error
    at Request._failAllPendingRequest (/opt/chat/node_modules/padlocal-client-ts/dist/Request.js:265:19)
    at ClientDuplexStreamImpl.<anonymous> (/opt/chat/node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (node:events:394:28)
    at Object.onReceiveStatus (/opt/chat/node_modules/@grpc/grpc-js/build/src/client.js:410:28)
    at Object.onReceiveStatus (/opt/chat/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /opt/chat/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by suntong** [comment]
> 本地macbook没问题，但是放到centos服务器上不论什么IP都无法登录

Some servers are just not working. They are blocked by TX. Try different ones.

**Comment by zzxiaotian** [comment]
22:04:22 INFO [PadLocalDemo] onScan: Timeout(5)
22:04:22 ERR [Request] [tid:4dd9ebe8], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:4dd9ebe8] check qr code timeout
22:04:22 ERR start client failed: VError: [tid:4dd9ebe8] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:4dd9ebe8] check qr code timeout
    at Request._failAllPendingRequest (/home/user/wecat/node_modules/padlocal-client-ts/src/Request.ts:338:15)
    at ClientDuplexStreamImpl.<anonymous> (/home/user/wecat/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:513:28)
    at ClientDuplexStreamImpl.emit (node:domain:489:12)
    at Object.onReceiveStatus (/home/user/wecat/node_modules/@grpc/grpc-js/src/client.ts:701:18)
    at Object.onReceiveStatus (/home/user/wecat/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /home/user/wecat/node_modules/@grpc/grpc-js/src/resolving-call.ts:11

**Comment by fdslk** [comment]
> 22:04:22 INFO [PadLocalDemo] onScan: Timeout(5) 22:04:22 ERR [Request] [tid:4dd9ebe8], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:4dd9ebe8] check qr code timeout 22:04:22 ERR start client failed: VError: [tid:4dd9ebe8] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:4dd9ebe8] check qr code timeout at Request._failAllPendingRequest (/home/user/wecat/node_modules/padlocal-client-ts/src/Request.ts:338:15) at ClientDuplexStreamImpl. (/home/user/wecat/node_modules/padlocal-client-ts/src/Request.ts:82:12) at ClientDuplexStreamImpl.emit (node:events:513:28) at ClientDuplexStreamImpl.emit (node:domain:489:12) at Object.onReceiveStatus (/home/user/wecat/node_modules/@grpc/grpc-js/src/client.ts:701:18) at Object.onReceiveStatus (/home/user/wecat/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48) at /home/user/wecat/node_modules/@grpc/grpc-js/src/resolving-call.ts:11

我也遇到了同样的问题

<img width="1430" alt="Image" src="https://github.com/user-attachments/assets/ba61f723-0a0f-49bc-83e7-159abc4c19c2" />
